name: build-test-XIOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_test:
    name: build XIOS and run tests
    runs-on: ubuntu-24.04
    steps:
      # Check out PR
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            sudo apt update
            sudo apt -yq install $(<dependencies)
      - name: build XIOS
        run: |
          ./make_xios --job 2 --debug --arch GCC_LINUX_APT
          ls -l bin/
      - name: run xios_test_suite
        run: |
          export GITHUB_ACTION_LIMIT_RANKS=1
          python3 -m xios_test_suite.pyTestingFramework
